# Form implementation generated from reading ui file 'C:\Users\oraveczl\PycharmProjects\OlympusGUI\ui\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.log = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.horizontalLayout.addWidget(self.log)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(parent=self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionE_xit = QtGui.QAction(parent=MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.actionConnect_camera = QtGui.QAction(parent=MainWindow)
        self.actionConnect_camera.setObjectName("actionConnect_camera")
        self.actionConnect_MockService = QtGui.QAction(parent=MainWindow)
        self.actionConnect_MockService.setObjectName("actionConnect_MockService")
        self.actionCamera_properties = QtGui.QAction(parent=MainWindow)
        self.actionCamera_properties.setObjectName("actionCamera_properties")
        self.action_About = QtGui.QAction(parent=MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Settings = QtGui.QAction(parent=MainWindow)
        self.action_Settings.setObjectName("action_Settings")
        self.menu_File.addAction(self.actionConnect_camera)
        self.menu_File.addAction(self.actionConnect_MockService)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionCamera_properties)
        self.menu_File.addAction(self.action_Settings)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit"))
        self.actionConnect_camera.setText(_translate("MainWindow", "Connect camera"))
        self.actionConnect_MockService.setText(_translate("MainWindow", "Connect MockService"))
        self.actionCamera_properties.setText(_translate("MainWindow", "Camera properties..."))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_Settings.setText(_translate("MainWindow", "&Settings..."))
